timezone: null
custom_base_url: null
languages:
  supported:
    - en
    - id
  default_lang: en
  include_default_lang: false
pages:
  theme: hadron-milkboy
  append_url_extension: null
  redirect_default_code: '302'
cache:
  redis:
    socket: ''
errors:
  display: 1
images:
  cls:
    retina_scale: '1'
gpm:
  verify_peer: true
updates:
  safe_upgrade: true
  safe_upgrade_snapshot_limit: 5
